Rails:
  Enabled: true

# saveの返り値チェック忘れを防ぎたい
# 失敗することがほぼないならsave!をつかう
Rails/SaveBang:
  Enabled: true

# なるべくRuby標準のメソッドを使う
Rails/SafeNavigation:
  ConvertTry: true

# マイグレーションのdownを使うことがないため
# わざわざreversibleにする理由がない
Rails/ReversibleMigration:
  Enabled: false
